apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-consumer-scaledobject
  namespace: kafka

spec:
  scaleTargetRef:
    name: consumer-deployment
  # pollingInterval: 5
  # cooldownPeriod: 10
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka.kafka.svc.cluster.local:9092
      topic: mytopic
      consumerGroup: my-consumer-group
      lagThreshold: "5" # number of unprocessed messages in kafka topic